# AUTO-GENERATED new content

NEW_CID_NAMES = {
    "souls_like": [
        "Protocolo da Fogueira Perpétua",
        "Herança do Muro Invisível",
        "Credo do Segundo Fase",
        "Fenômeno da Rolagem Sagrada",
        "Síndrome da Mensagem no Chão",
        "Tese da Barra de Stamina Insuficiente",
        "O Evangelium da Morte Número 999",
    ],
    "fps_competitivo": [
        "Vetor de Culpa Transferida",
        "Impulso do Rank Fantasma",
        "Decreto de Crosshair Eterno",
        "Liturgia do Peek Impossível",
        "Código do Smurf Reencarnado",
        "Fenômeno da Desconexão Estratégica",
        "Modo Warm-Up Eterno",
        "O Atlas do Recoil",
    ],
    "hero_shooter": [
        "Complexo do Main Incompreendido",
        "Ritual do Pick Dramático",
        "Parasita do Contador de Kills",
        "Assinatura da Ult Desperdiçada",
        "Estado de Flex Forçado",
        "Código do Duo Abandônico",
        "Fenômeno do Countering Ignorado",
        "O Grande Unificado da Meta",
    ],
    "arpg": [
        "Obsessão da Build Teórica",
        "Culto do Loot Perfeito",
        "Tese do Personagem Errado",
        "Modo Turbo-Limpeza de Mapa",
        "Decreto da Resistência Elemental",
        "Modo Resistência ao Tutorial",
        "Herança da Habilidade Nunca Usada",
        "A Constituição da Build Impossível",
    ],
    "battle_royale": [
        "Pacto do Círculo Final",
        "Instinto do Looter Tardio",
        "Fenômeno do Terceiro Elemento",
        "Reação de Queda Antecipada",
        "Eclipse do Inventário no Momento Errado",
        "Instinto do Sniper Sem Mira",
        "Assinatura da Voz Muda",
        "O Decreto do Chicken Dinner Vazio",
    ],
    "sandbox": [
        "Hábito da Construção Infinita",
        "Liturgia da Mina Profunda",
        "Modo Redecoration Perpétuo",
        "Vetor da Fazenda Nunca Colhida",
        "Código da Redstone Impossível",
        "Parasita do Projeto Nunca Finalizado",
        "A Catedral de Areia",
    ],
    "survival": [
        "Resposta de Acúmulo Preventivo",
        "Sintoma do Base Relocator Crônico",
        "Impulso da Noite Mal Calculada",
        "Parasita da Exploração Prematura",
        "Estado de Fome Ignorada",
        "Ritual da Dificuldade Ajustada",
    ],
    "rpg": [
        "Complexo do Diálogo Exaustivo",
        "Mania do Alinhamento Moral Inconsistente",
        "Ritual do Salvamento Compulsivo",
        "Assinatura do Personagem Errado na Hora Errada",
        "Tese do NPC Que Merecia Mais",
        "Eclipse do Mapa Não Consultado",
        "A Enciclopédia do NPC Genérico",
    ],
    "esporte": [
        "Protocolo da Formação Imutável",
        "Hábito do Transfer Arrependido",
        "Decreto do Replay Infinito",
        "Estado de Confiança Mal Calibrada",
        "Mania da Personalização Estética",
        "Tese do Goleiro Sacrificado",
        "Impulso da Substituição Atrasada",
        "A Temporada Perfeita Não Reconhecida",
    ],
    "roguelike": [
        "Culto da Run Perdida",
        "Ritual do 'Essa É A Run'",
        "Instinto Anti-Construção",
        "Síndrome do Item Preterido",
        "Fenômeno da Morte Absurda",
        "Decreto do Boss Derrotado com Raiva",
        "Estado de Sinergia Descoberta Tarde",
        "Manifesto da Run Ascendente",
    ],
    "simulador": [
        "Vetor da Realidade Simulada Preferível",
        "Liturgia do Lucro Mínimo",
        "Modo Perfeccionismo de Trem",
        "Código do NPC Favorito",
        "Hábito da Especialização Absurda",
        "Culto da Avaliação Cinco Estrelas",
        "Tese da Cidade Planificada",
        "A Grande Convergência do Trem 7",
    ],
    "visual_novel": [
        "Estado de Apego Ao Personagem Proibido",
        "Ritual da Rota Canônica",
        "Parasita do Skip Culposo",
        "Tese do Final Incorreto",
        "Eclipse do Relacionamento Paralelo",
        "Fenômeno da Rota Não Escolhida",
        "Ritual da Pausa Antes da Escolha",
        "O Fandom de Um",
    ],
    "estrategia": [
        "Fenômeno do 'Mais Uma Rodada'",
        "Código da Árvore de Tecnologia Inacabada",
        "Resposta de Aliança Indevida",
        "Impulso do Exército Simbólico",
        "Mania da Microgestão Terminal",
        "Herança do Líder Abandonado",
        "Modo Embargo Econômico Prematuro",
        "O Tratado de Paz Duradouro",
    ],
    "horror": [
        "Liturgia da Lanterna Vazia",
        "Hábito de Abrir a Porta Errada",
        "Vetor da Imunidade ao Próprio Medo",
        "Parasita do Stalker Ignorado",
        "Estado de Superstição Mecânica",
        "Assinatura do Corredor Longo Ignorado",
        "Complexo do Inventário em Pânico",
        "O Arquivo do Terror Catalogado",
    ],
    "plataforma": [
        "Código do Pulo Mal Calculado",
        "Ritual da Fase que Não Termina",
        "Instinto do Colecionável Impossível",
        "Fenômeno do Speedrun Acidental",
        "Eclipse do Inimigo Que Respawna",
        "Sintoma do Checkpoint Rejeitado",
        "Liturgia do Boss Pattern Memorizado",
        "A Equação do Pulo Perfeito",
    ],
    "mmo": [
        "Complexo da Guild Fantasma",
        "Assinatura do Crafting Sem Fim",
        "Ritual do Login Sem Propósito",
        "Modo Economia de Mercado Fanático",
        "Herança do Main com Identidade de Alt",
        "Vetor da Quest Abandonada",
        "Decreto do Pet Negligenciado",
        "Protocolo Omega do Servidor Morto",
    ],
}

NEW_SYMPTOMS = {
    "souls_like": [
        "O paciente demonstra incapacidade clínica de avançar sem primeiro retornar à fogueira mais próxima, mesmo sem motivo aparente. A fogueira tornou-se um útero emocional. Sentar ao lado do fogo não é descanso — é existência.",
        "O paciente acredita, com convicção inabalável, que existe uma parede secreta em cada canto do mapa. Bate em superfícies aleatórias com regularidade. Família relata preocupação com paredes do apartamento.",
        "O paciente desenvolveu uma resposta de choque pavloviana ao término de barras de vida de chefes. O coração acelera, as mãos suam, e uma voz interior grita 'não acabou' antes mesmo de qualquer indicação visual. O trauma é antecipatório.",
        "Fora do jogo, o paciente tenta mentalmente calcular iframes em situações cotidianas. Já 'rolou' mentalmente para evitar uma conversa desconfortável no trabalho. Relata sentir que o botão de esquiva deveria existir na vida real.",
        "O paciente passou a se comunicar em frases curtas, crípticas e de utilidade questionável. Deixou um bilhete na geladeira escrito 'cuidado à frente'. Quando perguntado sobre o jantar, respondeu 'tente fogo'.",
        "O paciente gasta toda a stamina atacando e não tem para esquivar. Morre. Gasta toda a stamina esquivando e não tem para atacar. Morre também. O equilíbrio é teórico. Na prática, sempre falta um ponto de stamina.",
        "O paciente morreu 999 vezes documentadas no mesmo chefe. Não desistiu. Não pediu ajuda. Não olhou guia. Na morte 1000, derrotou o chefe. Chorou. Ficou sentado olhando para a tela por 12 minutos. A experiência transcendeu o entretenimento e entrou em território espiritual não mapeado pela psicologia clínica tradicional.",
    ],
    "fps_competitivo": [
        "O paciente possui capacidade sobre-humana de identificar a falha de todos os membros do time exceto a própria. Produz relatórios mentais detalhados sobre os erros alheios durante a partida. Nunca assiste ao próprio replay.",
        "O paciente acredita genuinamente que seu rank atual não reflete sua habilidade real. Essa crença é mantida em todos os ranks já alcançados, retroativamente. Nunca houve um rank justo. Nunca haverá.",
        "O paciente passa mais tempo ajustando a mira do que jogando. Possui 47 perfis de crosshair salvos. Cada um foi 'o definitivo' por aproximadamente 20 minutos. A busca continua.",
        "O paciente foi morto pelo mesmo ângulo 11 vezes na mesma sessão. Na 12ª tentativa, tentou novamente. Quando questionado sobre a definição de insanidade, ficou quieto por tempo clinicamente relevante.",
        "O paciente cria contas alternativas com a justificativa de 'relaxar', mas entra em modo hipercompetitivo nos primeiros 30 segundos. Nunca relaxou. Não sabe o que é relaxar. O conceito lhe é estranho como um idioma alienígena.",
        "O paciente desconecta antes do fim de partidas perdidas por razões técnicas que apresentam correlação suspeitamente alta com o placar. A conexão é estável em vitórias. Instável em derrotas. O padrão é estatisticamente notável.",
        "O paciente passa 45 minutos no treino de mira 'se aquecendo' antes de cada sessão ranqueada. Quando finalmente entra na partida, ainda não está 'pronto'. O aquecimento é um ritual. O jogo, um apêndice.",
        "O paciente mapeou manualmente os padrões de recuo de todas as 47 armas do jogo, incluindo variações por distância, superfície, e estado de movimento. O documento tem 89 páginas. Foi publicado em fórum. Tem 340.000 visualizações. O paciente ainda é Gold 2.",
    ],
    "hero_shooter": [
        "O paciente mainou o mesmo personagem por 800 horas e ainda assim é votado para kickar após cada derrota. Desenvolveu uma teoria elaborada de que o jogo foi desenhado especificamente contra ele.",
        "O paciente trata a tela de seleção de personagens como uma declaração de identidade existencial. Cada pick comunica algo. O que exatamente, nem o paciente sabe, mas a intenção está lá.",
        "O paciente ignora objetivos ativamente para perseguir kills adicionais. Quando o time perde por não capturar o ponto, apresenta com orgulho sua pontuação individual. A palavra 'objetivo' parece não processar normalmente em seu córtex.",
        "O paciente possui instinto infalível para usar a ultimate no pior momento possível. Guarda por cinco minutos. Usa quando o time já ganhou o teamfight. Repete. O padrão é tão consistente que beira o talento.",
        "O paciente sempre 'flecha' para o que o time precisa mesmo odiando profundamente o papel. Joga suporte com fúria contida. Cada cura é um ato de resignação. A abnegação virou ressentimento crônico.",
        "O paciente pede duo ao amigo, entra em fila, e 15 minutos depois está jogando sozinho sem explicação. Quando o amigo pergunta, diz 'achei que ia levar mais tempo'. O amigo já esperava isso. Todos esperavam.",
        "O paciente continua jogando com o mesmo personagem mesmo sendo hard-countered pelo time adversário, por lealdade ao main. Morre 14 vezes. Não troca. A identidade do personagem supera a lógica da desvantagem mecânica.",
        "O paciente publicou uma análise de 80 páginas sobre equilíbrio do jogo que previu corretamente 11 dos 14 patches seguintes. A equipe de desenvolvimento seguiu o documento sem saber de sua existência. Quando confrontados com isso, a empresa disse que era coincidência. O paciente tem os timestamps. O debate ainda não foi resolvido.",
    ],
    "arpg": [
        "O paciente passa mais tempo planejando builds em planilhas externas do que efetivamente jogando. Possui 12 personagens no nível 30 com builds diferentes. Nenhum passou da campanha. O processo é o destino.",
        "O paciente não consegue deletar itens 'porque talvez precisem'. O inventário está 100% cheio há semanas. A crise existencial de dropar um item 'bom mas não ótimo' gera paralisia clínica de até 40 minutos.",
        "O paciente chega ao mid-game e conclui que sua classe estava errada desde o início. Recomeça com outra. Chega ao mesmo ponto. Conclui que essa também estava errada. O ciclo se repete com ritmo sazonal.",
        "O paciente não avança enquanto houver um único inimigo não eliminado no mapa atual. A narrativa é secundária. O mapa limpo é primário. A história pode esperar. Os inimigos não podem.",
        "O paciente verifica resistências elementais antes de qualquer decisão de jogo, antes de dormir, e ocasionalmente ao acordar. Sonhou com caps de resistência duas vezes neste mês. O médico não entendeu a relevância.",
        "O paciente pula todos os tutoriais porque 'já sabe como funciona'. Não sabe. Descobre que não sabe 4 horas depois em uma mecânica que o tutorial explicaria em 2 minutos. Não admite. Pesquisa no Reddit em sigilo.",
        "O paciente tem uma habilidade no slot que nunca usa mas que 'é boa para emergências'. As emergências chegaram. A habilidade não foi usada. A emergência passou. A habilidade aguarda a próxima, pacientemente.",
        "O paciente descobriu uma combinação de itens, habilidades e mecânicas que gera dano matematicamente infinito em condições específicas impossíveis de replicar em combate real. Escreveu um documento de 40 páginas provando a teoria. O desenvolvedor confirmou o bug. Foi patcheado. O paciente não ficou triste. A teoria ainda era verdadeira.",
    ],
    "battle_royale": [
        "O paciente evita todo conflito durante 90% da partida, posicionando-se estrategicamente. Quando chegam ao top 3 sem ter atirado uma vez, entram em pânico existencial e morrem de forma espetacularmente desnecessária.",
        "O paciente pousa em áreas vazias por segurança, passa 10 minutos coletando equipamentos mediocres, e morre para o primeiro oponente equipado que encontra. Repete. A estratégia é consistente. Os resultados, também.",
        "O paciente possui talento singular para aparecer em fights alheias exatamente quando ambos os lados estão fraquejando. Chama isso de 'estratégia'. Os outros chamam de outra coisa. Nenhum dos dois está errado.",
        "O paciente sempre pula do avião no primeiro segundo possível, independente do círculo, do loot disponível, ou de qualquer dado logístico. A lógica é: chegar primeiro. A consequência é: morrer primeiro.",
        "O paciente abre o inventário para organizar itens durante tiroteios ativos. A tela de derrota frequentemente aparece com o cursor ainda sobre um bandagem. O timing é consistentemente catastrófico.",
        "O paciente pega sniper rifle em todo loot possível apesar de possuir histórico confirmado de incapacidade com armas de longa distância. A teoria é que desta vez será diferente. Os dados discordam unanimemente.",
        "O paciente tem microfone, usa fones, e vê as jogadas erradas do time em tempo real mas nunca comunica nada. Após a derrota, lista internamente todas as informações que poderia ter compartilhado. A lista é longa. O microfone, intacto.",
        "O paciente ganhou 500 partidas seguidas sem sentir prazer em nenhuma delas. Ganhar virou procedimento. A tela de vitória é processada como um relatório financeiro. Tentou perder intencionalmente para sentir algo. Não conseguiu perder. A competência é agora um fardo existencial.",
    ],
    "sandbox": [
        "O paciente começou um projeto de construção há 6 meses que 'ainda não está pronto'. A estrutura tem 47 andares, nenhuma função definida, e beleza inquestionável. Perguntar quando termina gera resposta evasiva.",
        "O paciente cava em direção ao núcleo do mapa sem destino declarado. Quando perguntado o que procura, a resposta é 'não sei ainda'. A busca é o ponto. O mineral raro é só um pretexto para continuar descendo.",
        "O paciente reconstrói a mesma sala 14 vezes porque 'não ficou certo'. Cada versão era objetivamente funcional. Nenhuma era subjetivamente satisfatória. O padrão sugere que a sala perfeita pode não existir neste plano de realidade.",
        "O paciente plantou 200 itens de colheita que nunca foram colhidos porque 'não era o momento certo'. As plantas estão esperando. Ele também está esperando. Nenhum dos dois sabe o que espera.",
        "O paciente está construindo um computador funcional dentro do jogo. Apenas ele entende o diagrama. Quando tenta explicar, as pessoas piscam lentamente e mudam de assunto. Ele continua. O computador vai rodar Doom.",
        "O paciente tem 8 projetos ativos no mundo sandbox, todos em estado de 70% de conclusão. Nenhum será finalizado. Cada novo projeto é mais interessante que completar o anterior. A fundação de cada um é sólida. O teto, opcional.",
        "O paciente construiu uma catedral em um servidor de sandbox que levou 3 anos. Cada vitral é feito de blocos coloridos individualmente. O órgão virtual tem 2000 tubos funcionais. Nenhum outro jogador visitou. O servidor foi aberto ao público há 2 anos. O link foi postado uma vez. Teve 3 cliques.",
    ],
    "survival": [
        "O paciente nunca usa recursos porque 'pode precisar depois'. O estoque tem 847 bandagens e zero foram utilizadas. Morreu de fome com comida no inventário três vezes esta semana. A lógica do acúmulo sobrepõe o instinto de sobrevivência.",
        "O paciente constrói uma base, passa dias a fortalecer-la, e então decide que o local não é ideal. Desmonta tudo. Constrói em outro lugar. O processo se repete com a regularidade de uma estação.",
        "O paciente invariavelmente está longe da base quando o sol começa a se por. Corre. Não chega. Morre. No dia seguinte, repete o mesmo ciclo com a mesma confiança irredutível de que desta vez será diferente.",
        "O paciente explora zonas de alto nível com equipamento básico porque 'vou só olhar'. A sessão termina invariavelmente em morte humilhante. A próxima sessão começa com 'vou só olhar de novo'.",
        "O paciente deixa a barra de fome chegar a zero durante construções elaboradas porque 'deixa eu terminar isso primeiro'. O personagem desmaia de fome a dois blocos da mesa de crafting. Acontece toda semana.",
        "O paciente diminui a dificuldade após morrer repetidamente e imediatamente sente remorso. Joga na dificuldade mais baixa com a expressão de alguém que fez algo questionável. Ganha. Não comemora. A vitória tem asterisco.",
    ],
    "rpg": [
        "O paciente clica em todas as opções de diálogo disponíveis com cada NPC, incluindo opções claramente irrelevantes, para garantir que 'não perdeu nada'. Uma conversa de 3 minutos levou 40. O NPC pareceu cansado.",
        "O paciente tenta manter um alinhamento 'bom' mas cede ao saque de cada vila que encontra. O personagem oscila entre paladino e saqueador a cada 20 minutos. O sistema de karma entrou em colapso narrativo.",
        "O paciente salva o jogo antes de cada conversa, cada porta, cada escada, e cada NPC com aparência suspeita. Possui 340 saves manuais. O slot de quicksave é usado a cada 4 segundos. O HD geme.",
        "O paciente vai direto para a área final do jogo no nível 15 porque 'parecia o caminho'. Morre 30 vezes. Pesquisa online. Descobre que deveria estar no nível 60. Volta. Nunca esquece.",
        "O paciente desenvolveu apego emocional clinicamente relevante a personagens secundários com 4 linhas de diálogo. Ficou parado olhando para a tela por 8 minutos após a morte de um ferreiro de nome genérico.",
        "O paciente recusa-se a usar o mapa por princípio de imersão. Está perdido há 25 minutos. Sabe que está perdido. O princípio se mantém. Em algum lugar há uma cidade. Ele vai encontrá-la.",
        "O paciente escreveu uma enciclopédia de 200 páginas sobre os NPCs anônimos de um RPG, baseada em suas linhas de diálogo repetitivas. Criou narrativas, famílias, motivações e arcos dramáticos para personagens chamados 'Fazendeiro' e 'Guarda da Cidade'. A enciclopédia tem prefácio.",
    ],
    "esporte": [
        "O paciente usa a mesma formação há 3 temporadas independente do resultado. Quando perde, culpa os jogadores. Quando ganha, valida a formação. O raciocínio é circular e inabalável como uma obra de arte.",
        "O paciente vende seu melhor jogador por uma oferta absurda, investe em três mediocres, e passa a temporada inteira com remorso. O ciclo se repete anualmente com a pontualidade de um feriado.",
        "O paciente assiste ao replay do gol sofrido pelo menos 6 vezes, analisando cada falha com a seriedade de um tribunal esportivo. As conclusões nunca mudam nada. O processo, porém, é catártico de forma discutível.",
        "O paciente realiza jogadas de risco extremo com 1x0 no último minuto 'porque funciona'. A estatística histórica pessoal contradiz essa crença em 94% dos casos. O 6% restante alimenta o mito.",
        "O paciente passa mais tempo escolhendo o uniforme, as chuteiras e o estádio do que jogando. O time tem o visual mais elaborado da liga. A tabela classificatória não reflete isso de nenhuma forma.",
        "O paciente culpa o goleiro por todo gol sofrido, independente das circunstâncias. Um gol de 50 metros? Culpa do goleiro. Uma falha defensiva de 5 jogadores? Goleiro. A responsabilidade foi terceirizada há muito tempo.",
        "O paciente mantém jogadores cansados em campo por lealdade emocional com a performance histórica deles. O jogador está a 55% de eficiência. O paciente está a 100% de fidelidade irracional. O resultado está a 0%.",
        "O paciente ganhou uma liga inteira em um simulador esportivo com uma equipe de orçamento mínimo, formação alternativa, e sem nenhum jogador famoso. O time foi chamado de 'Rejeitos' ironicamente. Venceu tudo. Escreveu um livro de táticas de 120 páginas que ninguém leu. O livro está preciso. O jogo foi descontinuado.",
    ],
    "roguelike": [
        "O paciente ainda fala, meses depois, de uma run específica que foi interrompida por uma morte considerada 'injusta'. A narrativa foi refinada com o tempo. Hoje é uma lenda. Os fatos originais são irrelevantes.",
        "O paciente anuncia no início de cada sessão que 'essa é a run'. Com regularidade impressionante, não é. A frase perdeu significado, mas é pronunciada com fé renovada a cada vez.",
        "O paciente rejeita builds óbvias e sinergias claras por princípio. Experimenta combinações absurdas 'para ver o que acontece'. Morre. Anota mentalmente. Considera informação valiosa. Morre de novo.",
        "O paciente escolhe o item errado no shop, percebe isso imediatamente, e passa o resto da run com ressentimento latente em relação ao item que não pegou. A run pode até ir bem. O ressentimento permanece.",
        "O paciente tem um acervo mental de mortes ridículas — mortos por dano de ambiente, por inimigo fora de tela, por skill própria, por lag. Cada morte é catalogada com precisão forense e vergonha adequada.",
        "O paciente derrota o chefe final depois de 50 tentativas e em vez de sentir alegria experimenta uma estranha combinação de exaustão, raiva residual e vazio. A vitória chegou. O sentimento certo, não.",
        "O paciente descobre uma sinergia poderosa de build no último andar do jogo, quando já é tarde para aproveitá-la completamente. O entendimento chegou. O timing, não. A próxima run será diferente. Desta forma específica.",
        "O paciente completou o roguelike em todas as dificuldades, com todos os personagens, em todas as combinações de modificadores, incluindo modos de desenvolvimento não oficialmente suportados. Enviou um relatório de bugs ao desenvolvedor. O desenvolvedor respondeu. Tornaram-se amigos. O jogo foi balanceado a partir do feedback. O paciente não recebeu créditos. Não pediu.",
    ],
    "simulador": [
        "O paciente demonstra mais prazer gerenciando a fazenda virtual do que qualquer aspecto da vida fora dela. A planta virtual é regada com pontualidade que a planta real jamais recebeu. O médico não entendeu o problema.",
        "O paciente vende itens no simulador de negócios pelo menor preço possível porque 'não quer ser ganancioso'. A empresa está tecnicamente falindo em um jogo sobre enriquecer. Os concorrentes digitais agradecem.",
        "O paciente redesenha a malha ferroviária do simulador de trens pela 8ª vez porque uma curva estava 'ligeiramente errada esteticamente'. Nenhum trem colidiu. Nenhum passageiro reclamou. A curva, porém, incomodava.",
        "O paciente desenvolveu narrativa pessoal para um NPC específico do simulador de cidade. Tem nome, backstory e motivações. O NPC é um sprite que anda em loop de 8 passos. O paciente está bem. Provavelmente.",
        "O paciente jogou o simulador de caminhão por 400 horas e escolheu especializar-se apenas em entregas noturnas de produtos lácteos. Há uma comunidade pequena com quem conversa sobre isso. Isso é confortante de alguma forma.",
        "O paciente reinicia qualquer serviço no simulador que resulte em avaliação abaixo de 5 estrelas, mesmo que a diferença seja mínima e o impacto no jogo seja nulo. Uma estrela a menos é uma falha moral.",
        "O paciente passou 6 horas apenas planejando a cidade no papel antes de colocar um único edifício. Tem 3 versões do plano. A cidade tem zero habitantes. A infraestrutura está planejada para 2 milhões. O primeiro edifício ainda não foi colocado.",
        "O paciente construiu uma rede ferroviária de 847 estações em um simulador de trens que funciona em tempo real. O sistema nunca teve um atraso. Cada trem tem nome pessoal. Há uma cerimônia informal quando um trem novo é comissionado. A família não foi convidada para a cerimônia.",
    ],
    "visual_novel": [
        "O paciente possui sentimentos elaborados por um personagem de visual novel que incluem ciúme de outros personagens ficcionais, alegria quando o personagem aparece, e irritação quando o roteirista faz escolhas 'erradas' com ele.",
        "O paciente leu todas as rotas do jogo mas afirma que apenas uma é 'a verdadeira'. Discute isso online com fervor teológico. As outras rotas existem como heresias toleradas.",
        "O paciente usou o skip em diálogos que já leu e imediatamente sentiu culpa difusa. Voltou atrás para 'dar uma chance' ao texto que já conhecia. Leu de novo. Confirmou que era igual. Ficou em paz.",
        "O paciente completou o jogo com o final 'verdadeiro' mas considerou errado. Escreveu uma continuação alternativa em fórum especializado. Tem 47 páginas. Tem seguidores. O escritor original não foi consultado.",
        "O paciente tenta manter relacionamento máximo com todos os personagens simultaneamente, causando conflitos narrativos que ele resolve com múltiplos saves. Cada save corresponde a uma vida paralela. Ele visita todas elas.",
        "O paciente escolheu uma rota e agora pensa constantemente no que teria acontecido na outra. A curiosidade é maior que a satisfação com o final obtido. A completude seria a solução. O completismo, o problema.",
        "O paciente pausa o jogo por vários minutos antes de cada escolha importante, mesmo em segundas releituras onde já sabe o resultado. A deliberação não muda nada. O ritual é necessário. A resposta, inevitável.",
        "O paciente mantém um site dedicado a uma visual novel de 2007 com zero atualizações do desenvolvedor. O site tem fanarts, fanfics, análises, e um fórum com 1 usuário ativo: ele mesmo. Responde os próprios posts de anos atrás com perspectivas atualizadas.",
    ],
    "estrategia": [
        "O paciente prometeu parar às 22h. São 4h da manhã. Ele está fundando sua quinta civilização. A promessa foi feita com sinceridade. O problema é que cada rodada gera outra rodada, infinitamente, até o colapso biológico.",
        "O paciente pesquisa tecnologias sem ordem estratégica, seguindo curiosidade pura. Tem astronomia avançada e arco e flecha básico. A civilização é inconsistente mas interessante como objeto de estudo.",
        "O paciente faz alianças com todas as facções disponíveis, acreditando que isso traz paz. As facções trairão umas às outras. O paciente ficará no meio. Isso ocorreu 7 vezes. Ele continua sendo otimista.",
        "O paciente constrói um exército enorme que nunca usa porque 'prefere diplomacia'. O exército existe como símbolo. Os inimigos não respeitam símbolos. A capital foi tomada por uma tribo com lanças.",
        "O paciente controla manualmente cada trabalhador, cada rota de recurso, cada patrulha militar. O império tem 400 cidadãos. Cada um tem função designada manualmente. O jogo deveria ter terminado há 6 horas.",
        "O paciente herdou uma partida salva de outro jogador e agora se sente responsável por 'não decepcionar' as decisões tomadas anteriormente, mesmo discordando delas. Está respeitando escolhas de um estranho. Em um videogame.",
        "O paciente impõe sanções comerciais a um adversário mais forte antes de ter infraestrutura adequada. A guerra econômica começa. O paciente perde. A estratégia era correta teoricamente. O timing era catastrófico praticamente.",
        "O paciente ganhou um jogo de estratégia de conquista sem declarar uma única guerra em toda a partida. Usou exclusivamente diplomacia, casamentos reais, pressão econômica e espionagem. A vitória foi por pontos culturais após 600 turnos. O jogo sugeriu que era quase impossível. O paciente não sabia disso.",
    ],
    "horror": [
        "O paciente deixa a bateria da lanterna chegar a zero por recusar-se a economizá-la. Fica no escuro. Caminha no escuro. Morre no escuro. Na próxima sessão, repete o comportamento com fé renovada na lanterna.",
        "O paciente sabe que a porta à esquerda tem o monstro. Todos os indicadores apontam isso. Ele abre mesmo assim 'para confirmar'. Confirma. Morre. Na próxima sala, há outra porta. O processo reinicia.",
        "O paciente começou o jogo de horror gritando. Após 4 horas, pasta de dente no susto. Após 8 horas, debate a hitbox do monstro enquanto morre. A dessensibilização foi total. O jogo, ironicamente, perdeu sentido.",
        "O paciente acredita que se ignorar o inimigo que o persegue, ele vai embora. Esta crença não tem base no design do jogo, na lógica do gênero, ou em qualquer evidência empírica. Morreu assim 4 vezes. Tenta de novo.",
        "O paciente desenvolveu rituais pessoais para 'ajudar' no jogo de horror: entrar em cada sala em pé quieto por 3 segundos, verificar os cantos na mesma ordem sempre, nunca correr em corredor longo sem olhar para trás. Funciona? Talvez. Provavelmente não.",
        "O paciente corre pelo corredor comprido e assustador sem olhar para os lados porque 'se não vir, não existe'. Este é filosoficamente questionável como estratégia de sobrevivência. Funcionou duas vezes. Isso foi suficiente.",
        "O paciente abre o inventário em momentos de terror intenso como resposta de fuga. A ação de gerenciar itens é calmante. Enquanto o monstro ruge do outro lado da porta, ele reorganiza ervas medicinais por ordem alfabética.",
        "O paciente criou um banco de dados de 3.000 entradas catalogando cada jumpscare de jogos de horror que jogou, com avaliações de eficácia, timing, contexto narrativo, e impacto emocional residual. Cita a base de dados em conversas casuais sobre filmes. As pessoas ficam em silêncio por um tempo.",
    ],
    "plataforma": [
        "O paciente tenta pulos que visualmente parecem impossíveis mas 'talvez dê'. Em 70% dos casos, não dá. Em 30%, dá, o que é suficiente para manter a esperança viva e os pulos continuando.",
        "O paciente está preso na mesma fase há 3 sessões. Sabe cada seção de cor. Pode descrever cada obstáculo de olhos fechados. Ainda cai no mesmo buraco. O corpo sabe o caminho. As mãos têm outra opinião.",
        "O paciente viu o colecionável em uma plataforma inacessível e decidiu imediatamente que vai conseguir. Duas horas depois, ainda está tentando. O jogo tem 200 colecionáveis. Este é o primeiro. O progresso narrativo parou.",
        "O paciente, ao tentar 'só passar logo por essa parte', descobriu um caminho alternativo que corta metade da fase. Passou 1 hora tentando replicar. Não conseguiu. Agora está em um fórum de speedrun sem ter planejado isso.",
        "O paciente tenta passar pelos inimigos sem matar nenhum por princípio ético discutível dentro de um jogo de plataforma. Morre. Recomeça. Os inimigos respawnaram. O princípio se mantém. O progresso, não.",
        "O paciente morre perto de um checkpoint mas escolhe reiniciar do começo 'para pegar o ritmo'. O ritmo nunca é adequado o suficiente. O jogo tem 15 checkpoints. O paciente os ignorou todos por princípio estético de valor questionável.",
        "O paciente memorizou todos os padrões do chefe mas ainda morre porque na hora H entra em pânico e esquece tudo. O conhecimento está lá. O acesso em situação de pressão, não. A teoria e a prática são continentes diferentes.",
        "O paciente passou 200 horas em um único segmento de plataforma que requeria timing perfeito, calculando matematicamente o frame exato necessário. Produziu um documento com equações reais de física aplicadas à mecânica do personagem virtual. O documento foi revisado por um professor de física. As equações estão corretas. O pulo ainda falha às vezes.",
    ],
    "mmo": [
        "O paciente é líder de uma guild de 1 pessoa. Mantém o banco da guild organizado, as regras postadas, e o nome escolhido com cuidado. Os outros membros partiram há anos. Ele atualiza o MOTD semanalmente.",
        "O paciente não participa de nenhum conteúdo multiplayer porque 'ainda está treinando crafting'. O crafting atingiu nível máximo há 2 meses. O pretexto permanece. O mundo multiplayer existe sem ele, funcionalmente.",
        "O paciente loga diariamente, fica parado na cidade principal observando o fluxo de outros jogadores, faz 2 quests menores, e desconecta. Não há objetivo definido. A presença é o objetivo. A cidade é o lar.",
        "O paciente não joga o jogo. Joga a casa de leilões. Monitora preços, especula em flutuações, e reinveste com metodologia. Tem mais ouro do que qualquer jogador. Nunca saiu da cidade capital. Não sabe o nome do vilão principal.",
        "O paciente tem um personagem principal mas na prática joga mais o alt criado 'só para testar'. O main tem melhor equipamento. O alt tem mais horas. Perguntar qual é o favorito gera hesitação clínica de 8 segundos.",
        "O paciente tem 73 quests ativas que não pretende completar mas se recusa a abandonar 'porque nunca se sabe'. O log de quests é um museu de intenções antigas. Cada uma representa uma versão passada de si mesmo.",
        "O paciente tem um pet raro que foi conquistado com grande esforço e raramente é convocado porque 'não combina com o visual do personagem'. O pet aguarda no limbo digital, raro e invisível. O visual está impecável.",
        "O paciente continua logando em um MMO cujo servidor oficial foi desligado, em um servidor privado com 3 jogadores ativos, dos quais 2 são contas suas. Continua fazendo quests diárias. Atualiza o banco da guild. Escreve no fórum que tem 0 posts novos há 2 anos.",
    ],
}

NEW_PROGNOSIS = {
    "souls_like": [
        "Você não joga um souls-like. Você mora nele.",
        "Toda parede é uma porta que ainda não te mereceu.",
        "A segunda fase não é um obstáculo. É uma filosofia.",
        "Você não foge dos problemas. Você tem i-frames.",
        "A linguagem humana é optional. A mensagem no chão é eterna.",
        "A stamina estava quase cheia. O inimigo não esperou.",
        "Você não venceu o chefe. Você venceu a si mesmo. O chefe era só o pretexto.",
    ],
    "fps_competitivo": [
        "O problema é sistêmico. O sistema são os outros.",
        "Seu verdadeiro elo existe apenas em dimensões paralelas.",
        "A mira perfeita é uma metáfora. Ninguém sabe de quê.",
        "O peek vai funcionar. Só precisa de mais uma tentativa.",
        "Você veio para se divertir. Você ficou para dominar.",
        "Sua internet falha nos momentos mais inconvenientes. Curiosamente.",
        "Você se preparou por horas. Para 20 minutos de jogo. A proporção é nota-da-terapia.",
        "Você sabe mais sobre o jogo do que qualquer um. O rank não recebeu o documento.",
    ],
    "hero_shooter": [
        "Ser um main é um fardo. Ser um main é um chamado.",
        "Você não escolhe um herói. Você se revela.",
        "Você não joga para ganhar. Você joga para aparecer no resumo.",
        "Sua ult foi guardada com carinho. E usada sem necessidade.",
        "Você não curou o time. Você sofreu pelo time.",
        "Você convidou. Depois saiu. Essa é a dança.",
        "Você foi contrado. Ficou assim mesmo. Isso tem nome: lealdade ou teimosia. A fronteira é fina.",
        "Você previu o futuro do jogo. Ninguém acreditou. O futuro chegou de qualquer forma.",
    ],
    "arpg": [
        "Sua build está completa no papel. No jogo, mal começou.",
        "Você não joga um arpg. Você administra um armazém de ansiedade.",
        "O personagem certo existe. Você ainda não o encontrou. Talvez na próxima run.",
        "A história te chama. O minimapa ainda tem pontinhos.",
        "75% de resistência ao fogo. 0% de resistência ao jogo em si.",
        "Você não precisava do tutorial. Até precisar. Em silêncio.",
        "Ela está lá. Para quando você precisar. Você nunca precisou.",
        "O bug foi corrigido. A tese permanece. Você provou algo que não pode mais ser feito. Isso é ciência, de uma forma.",
    ],
    "battle_royale": [
        "Você sobreviveu a todos. Menos a você mesmo.",
        "Você estava preparado para tudo. Exceto para o combate.",
        "Você não venceu a luta. Você foi à luta depois que ela terminou.",
        "Você foi o primeiro a chegar. E o primeiro a sair.",
        "Seu inventário estava impecável. Sua saúde, nem tanto.",
        "Você acredita na sniper. A sniper não acredita em você.",
        "Você sabia de tudo. Disse nada. Era o suficiente para ganhar.",
        "Você dominou o jogo. O jogo perdeu o sentido. Agora o quê?",
    ],
    "sandbox": [
        "Você não está construindo uma casa. Está construindo uma identidade.",
        "Você está cavando. Você sempre esteve cavando.",
        "A sala anterior era boa. Esta será melhor. A próxima será a certa.",
        "A colheita chegará. Provavelmente. Talvez.",
        "Não é obsessão. É engenharia. Bem, é as duas coisas.",
        "Você começa muito bem. O final é um conceito teórico.",
        "A obra existe. Poucos a viram. A obra não precisa de audiência. Mas você talvez precisasse.",
    ],
    "survival": [
        "Você tinha tudo para sobreviver. Preferiu guardar.",
        "Sua base era sólida. Mas o horizonte parecia melhor.",
        "O dia foi longo. A noite foi mais longa. Você, mais curto.",
        "Você foi só dar uma olhada. Olhou. Morreu. Clássico.",
        "A construção estava ficando linda. Você estava ficando morto.",
        "Você ganhou. Você sabe como ganhou. Ambos sabem.",
    ],
    "rpg": [
        "Você leu tudo. Entendeu metade. Esqueceu o resto.",
        "Você é um herói. Exceto quando não é. Que é frequente.",
        "Você não joga com medo de perder. Você salva com medo de viver.",
        "O jogo te avisou. Você ignorou. Todos ignoram.",
        "Ele era só um ferreiro. Mas era o seu ferreiro.",
        "O mapa existe. Sua teimosia também. Uma delas é inútil aqui.",
        "Eles existiam por 4 pixels e 2 linhas. Você deu a eles um legado.",
    ],
    "esporte": [
        "A formação está certa. O universo que está errado.",
        "Você vendeu seu craque. Comprou potencial. Potencial não marca gol.",
        "O gol já foi. Você ainda está aqui, julgando.",
        "Na sua cabeça, você faz isso sempre. Nos dados, raramente.",
        "Seu time é lindo. Mas beleza não conta como ponto.",
        "O goleiro falhou. Todos falharam. Só o goleiro foi mencionado.",
        "Ele foi leal a você uma vez. Você ainda não esqueceu.",
        "Você provou que era possível. Para um público de zero. O resultado foi real.",
    ],
    "roguelike": [
        "A run existe agora apenas como mito. E o mito é perfeito.",
        "Você acredita. Isso, pelo menos, é consistente.",
        "Sua build era única. Era também inviável. Mas principalmente única.",
        "O item era bom. O outro seria melhor. Você nunca saberá.",
        "Você não perdeu. Você foi derrotado por circunstâncias.",
        "Você ganhou. Seu estado emocional não recebeu o memorando.",
        "Você entendeu. Cedo demais para agir. Tarde para esta run.",
        "Você não jogou um jogo. Você o compreendeu em dimensões que o criador não havia mapeado.",
    ],
    "simulador": [
        "Sua fazenda está prosperando. Sua vida real está esperando.",
        "Sua ética é admirável. Seu balanço financeiro, não.",
        "Os trens chegavam no horário. A curva chegava nos sonhos.",
        "Ele não sabe que existe. Você sabe por ambos.",
        "Você encontrou seu nicho. Ele é pequeno. É seu.",
        "Você tem 4.8 estrelas. Você recomeçou. Por 0.2.",
        "Sua cidade é perfeita. No papel. No jogo, existe a grade vazia.",
        "Você construiu um milagre de logística. Em um videogame. Isso não diminui o milagre.",
    ],
    "visual_novel": [
        "Ele não é real. Seu coração não foi avisado.",
        "O cânone é o que você decide. Você decidiu. Firmemente.",
        "Você já sabia o que dizia. Leu assim mesmo. Isso diz algo.",
        "O jogo terminou. A sua versão acabou de começar.",
        "Você amou todos. Em saves separados. Conta?",
        "Você seguiu um caminho. O outro ainda sussurra.",
        "Você pensou muito. Escolheu o mesmo. Era o único final que fazia sentido para você.",
        "O jogo ficou. Você ficou com ele. Num site que só você conhece. Isso é amor em sua forma mais pura e mais solitária.",
    ],
    "estrategia": [
        "Mais uma rodada. Sempre foi mentira. Sempre será.",
        "Você foi ao espaço. De barco a remo. Funcionou, de certa forma.",
        "Você confiou em todos. Eles confiaram em você... temporariamente.",
        "Seu exército estava pronto. Para um conflito que não veio do jeito esperado.",
        "Você controla tudo. Isso é poder. Também é exaustão.",
        "Você honrou as escolhas dele. Não eram suas. Não importou.",
        "Você sabia o que fazer. Fez cedo demais. O resultado é o mesmo.",
        "Você ganhou sem lutar. O jogo não esperava isso. Você também não. A vitória foi uma surpresa para todos.",
    ],
    "horror": [
        "A luz acabou. Você continuou. Não devia ter continuado.",
        "Você sabia. Abriu assim mesmo. Isso não é coragem. É algo diferente.",
        "Você não tem mais medo. Parabéns. Perdeu o ponto do gênero.",
        "Você fingiu que não estava lá. Ele continuou lá.",
        "Seu ritual é seu escudo. O monstro não sabe disso.",
        "O que você não viu talvez não te viu. Talvez.",
        "O monstro está chegando. Seus itens estão em ordem. Prioridades claras.",
        "O medo foi documentado, categorizado, e arquivado. Agora ele não tem mais poder sobre você. Mas o banco de dados cresceu.",
    ],
    "plataforma": [
        "O pulo era improvável. Você tentou. Às vezes é suficiente.",
        "Sua mente completou essa fase 400 vezes. Suas mãos, zero.",
        "Era um objeto sem utilidade. Você deu sua tarde para ele.",
        "Você não queria ser speedrunner. O jogo escolheu por você.",
        "Você tem valores. Os inimigos têm respawn. Um desses importa mais aqui.",
        "O checkpoint existia para você. Você existiu para ignorá-lo.",
        "Você sabia tudo. Seu cérebro apresentou demissão na hora do uso.",
        "A física estava certa. A execução ainda é humana. Isso não é falha da ciência.",
    ],
    "mmo": [
        "Você lidera com dedicação. Para ninguém. É impressionante assim mesmo.",
        "Você está quase pronto. Há meses. O mundo não esperou.",
        "Você foi lá. Ficou. Voltou. Isso foi suficiente hoje.",
        "Você dominou a economia. O jogo em si permanece um mistério.",
        "Você tem um main. E um alt. E o alt venceu.",
        "Você começou muitas histórias. Terminar é outra conversa.",
        "Seu pet é valioso. E invisível. Você escolheu o segundo.",
        "O mundo morreu. Você ainda vive nele. Isso é devotamento ou é outra coisa. Talvez ambos.",
    ],
}

