"""
Blocos de sintomas por categoria de jogo.
"""

SYMPTOMS: dict[str, list[str]] = {
    "souls_like": [
        "Masoca voluntário que chama de 'aprender a jogar' qualquer coisa que mata em 1 hit",
        "Nível de dopamina só sobe ao ouvir 'YOU DIED' pela 47ª vez seguida",
        "Explica mecânicas de boss com a seriedade de um cardiologista em plantão",
        "Acredita que todo jogo com modo fácil é um insulto pessoal direcionado a ele",
        "Usa a palavra 'mecânica' em contextos que não têm nada a ver com jogos",
        "Tem flashback de bosses ao ouvir qualquer música orquestral",
        "Considera 'pausa para o banheiro' uma fraqueza de caráter",
        "Descreve tortura psicológica voluntária como 'experiência artística única'",
        "Defende com veemência que qualquer jogo sem punição severa 'não tem alma'",
        "Passou mais tempo olhando para a tela de Game Over do que para qualquer série na Netflix",
        "O vocabulário do dia a dia inclui termos como 'parry window' e 'iframes' com naturalidade perturbadora",
        "Compra todo DLC de desafio adicional mesmo sabendo que vai sofrer — especialmente porque vai sofrer",
    ],
    "fps_competitivo": [
        "Culpa a hitbox, o ping, a cadeira, o mouse, o horóscopo e o clima por cada derrota",
        "Hardstuck no mesmo rank há 2 temporadas mas tem CERTEZA absoluta que é culpa dos teammates",
        "Passa mais tempo reclamando no chat do que com a mira no inimigo",
        "Comprou periféricos de R$3.000 e ainda joga igual um bot de tutorial",
        "Conhece as callouts do mapa de cor mas não sabe o nome da própria rua",
        "Tem mais opiniões sobre sens de mouse do que sobre qualquer assunto da vida real",
        "A expressão 'skill issue' é usada para TUDO menos para si próprio",
        "Desinstala o jogo em média 2.3 vezes por semana e reinstala no dia seguinte",
        "Acredita que assistir streamers pro vai transferir habilidade por osmose",
        "Diz 'fui hackeado' sempre que morre para alguém com aim melhor que o seu",
        "Já culpou o servidor, a Riot/Valve, o governo e Mercúrio retrógrado por uma derrota",
        "Analisa VODs de partidas próprias como se fosse preparação para um campeonato mundial",
    ],
    "hero_shooter": [
        "Tem opinião formada e extremamente vocal sobre cada personagem do roster — especialmente os que nunca jogou",
        "Trata o meta como lei federal e executa quem joga fora dele",
        "Já entrou em conflito familiar por causa de nerf de personagem favorito",
        "O termo 'balanceamento' provoca uma reação emocional desproporcional",
        "Acumula horas absurdas em um único herói e se recusa a aprender qualquer outro",
        "Considera skin rara um marcador legítimo de status social",
        "Já escreveu feedback para a desenvolvedora com linguagem de manifesto político",
        "Defende que a versão atual do jogo é sempre pior do que era antes",
    ],
    "arpg": [
        "Cria uma build nova a cada 3 dias porque a anterior 'não era a definitiva'",
        "Considera 1.000 horas de play 'ainda aprendendo o básico'",
        "Tem uma planilha de builds atualizada com mais rigor do que qualquer trabalho real",
        "Passa mais tempo no wiki do jogo do que jogando o jogo",
        "A palavra 'temporada' tem o mesmo peso emocional que uma reforma tributária",
        "Já recusou compromissos sociais por causa de reset de liga/temporada",
        "Compra o mesmo jogo em outra plataforma 'para jogar em outro momento'",
        "O inventário virtual está mais organizado que qualquer coisa no mundo físico",
        "Sente ansiedade genuína ao ver um item raro que não cabe no build atual",
    ],
    "battle_royale": [
        "Acredita que o círculo sempre fecha em cima dele de propósito",
        "Top 2 é considerado derrota. Não existe nuance entre isso e o #1",
        "Já calculou estatisticamente por que não é culpa sua nunca — e deu certo na planilha",
        "Passou mais tempo no lobby do que em partidas efetivas",
        "O estômago embrulha ao ouvir sons de zona encolhendo",
        "Tem teorias conspiratórias sobre o algoritmo de matchmaking",
        "Comprou skins para jogar melhor. Não funcionou. Comprou mais skins.",
    ],
    "sandbox": [
        "Incapaz de terminar qualquer coisa — começa uma nova base toda sessão",
        "Passa 4 horas organizando inventário antes de sair da toca inicial",
        "Construiu uma réplica do Palácio de Versalhes em vez de avançar no tutorial",
        "Definição de 'progresso': mais 200 blocos empilhados sem propósito definido",
        "Tem um mundo 'principal' e 12 mundos 'temporários' que nunca foram deletados",
        "O perfeccionismo construtivo resultou em abandono de 100% dos projetos iniciados",
        "Já assistiu tutoriais de construção por mais horas do que efetivamente construiu",
        "Considera frame rate consistente mais importante do que qualquer narrativa",
    ],
    "survival": [
        "Acorda às 3h preocupado se deixou a fogueira acesa no servidor",
        "Stockpile compulsivo — nunca usa nenhum item porque 'pode precisar depois'",
        "A barra de fome virtual causa mais ansiedade do que qualquer reunião de trabalho",
        "Relaciona o humor do dia com a quantidade de recursos no inventário",
        "Considera qualquer servidor PvP uma traição pessoal à humanidade",
        "Tem mais comida virtual estocada do que real na geladeira",
        "A palavra 'griefer' provoca uma resposta de estresse comparável a ameaça física",
        "Já ficou online por precaução para 'não perder a base' em um servidor com amigos",
    ],
    "rpg": [
        "Leva 2 horas no criador de personagem e abandona o jogo no tutorial",
        "Lê cada linha de diálogo de NPC mesmo em idioma que não entende",
        "Tem 3 saves paralelos porque comprometer-se com uma escolha é emocionalmente pesado",
        "Chama de 'imersão' o hábito patológico de nomear o protagonista com nome próprio",
        "Já reiniciou o jogo do zero por causa de uma escolha de diálogo que 'não era o que o personagem diria'",
        "Conhece a lore de personagens secundários com mais detalhe do que qualquer coisa da vida real",
        "Considera qualquer jogo sem árvore de habilidades 'raso demais para o seu nível'",
        "A expressão 'decisões com peso' provoca uma reação emocional visível",
        "Já pesquisou no Google qual escolha de diálogo é 'a certa' para depois sentir que foi mais autêntico",
    ],
    "esporte": [
        "Acredita genuinamente que vencer no FIFA o credencia a debater táticas com treinadores reais",
        "Xinga o árbitro virtual em voz alta como se ele pudesse revisar a decisão",
        "Ultimate Team consumiu mais dinheiro do que qualquer clube da série C gasta em contratação",
        "Confunde habilidade no jogo com aptidão física e conhecimento tático real",
        "Já tentou explicar uma derrota no jogo usando terminologia de futebol de campo com a família",
        "O calendário do ano é organizado em torno do ciclo de temporadas do jogo",
        "Tem opinião sobre jogadores reais baseada exclusivamente em ratings do FUT",
        "Já reclamou de 'injustiça' em um jogo feito por IA que não tem sentimento nenhum",
    ],
    "roguelike": [
        "Incapaz de aceitar derrota — chama cada run perdida de 'aquecimento'",
        "Sabe de cor cada pool de itens, cada seed ruim, e ainda perde na mesma sala",
        "A frase 'só mais uma run' é pronunciada em média 7 vezes antes de dormir",
        "Rejeita qualquer narrativa linear porque precisa de RNG para sentir que ainda está vivo",
        "Já recusou sair de casa porque estava em uma 'run boa demais para pausar'",
        "Considera qualquer run sem um item específico 'matematicamente perdida'",
        "O conceito de 'fim de jogo definitivo' não existe no modelo mental do paciente",
        "Já ficou acordado até as 4h porque a próxima run 'com certeza ia ser diferente'",
    ],
    "simulador": [
        "Prefere consistentemente a versão simulada da vida à própria vida",
        "Passou mais tempo simulando trabalho no jogo do que trabalhando de verdade",
        "A fazenda/cidade virtual está em estado de organização impossível na vida real",
        "Chama de 'relaxar' passar 6h gerenciando planilha agrícola ou orçamento municipal virtual",
        "Considera gerenciar uma cidade virtual de 500 mil habitantes 'menos estressante que o trabalho'",
        "Já cancelou planos para 'terminar uma rota' ou 'completar a temporada da fazenda'",
        "O ROI virtual é calculado com mais rigor do que qualquer finanças pessoal",
        "Recomenda Euro Truck Simulator como 'terapia' para pessoas com ansiedade",
    ],
    "visual_novel": [
        "Desenvolveu vínculo emocional mais profundo com personagem 2D do que com qualquer pessoa real nos últimos 6 meses",
        "Já chorou com um final de personagem que tecnicamente não existiu",
        "Recomenda o jogo descrevendo como 'é tipo livro, mas melhor' sem perceber o que isso diz sobre si",
        "Tempo médio de leitura: 40h. Quantidade de decisões difíceis tomadas na vida real: 0",
        "Tem screenshots de falas de personagens fictícios salvos como papel de parede",
        "Considera o jogo 'literatura interativa' quando questionado por não-gamers",
        "Já buscou 'guia de todas as rotas' antes de fazer qualquer escolha para não 'perder conteúdo'",
        "A trilha sonora do jogo provoca resposta emocional imediata e intensa fora de contexto",
    ],
    "estrategia": [
        "Passa mais tempo na fase de planejamento do que na batalha em si",
        "Gerencia exércitos e impérios virtuais com mais competência do que a própria agenda",
        "Lê guias de 45 páginas antes de fazer qualquer movimento em qualquer jogo",
        "O conceito de 'one more turn' é uma doença crônica sem cura documentada",
        "Já perdeu noção do tempo e ficou acordado até amanhecer 'terminando só essa guerra'",
        "Aplica terminologia de 4X em conversas cotidianas sem perceber",
        "Considera qualquer derrota 'um problema de macro' que nunca é culpa da micro",
        "Tem mais horas em tutoriais e campanhas iniciais do que em partidas completas",
        "O conceito de 'vitória' foi redefinido tantas vezes que não existe mais uma definição estável",
    ],
    "horror": [
        "Joga no mudo com o brilho no máximo e ainda assim chama de 'experiência completa'",
        "Leva 20 minutos para abrir cada nova porta, mesmo sabendo que nada vai acontecer",
        "Dorme com a luz acesa mas nega categoricamente qualquer relação com os jogos",
        "Compra cada DLC de horror no lançamento e joga exatamente 11 minutos antes de desinstalar",
        "Assiste outros jogarem no YouTube por 3h e depois afirma que 'já conhece o jogo'",
        "O reflexo de susto condicionado se ativou durante uma reunião de trabalho silenciosa",
        "Considera Phasmophobia 'um jogo tranquilo' e isso já diz tudo",
        "Já gritou em voz alta e assustou alguém na mesma casa durante uma sessão",
    ],
    "plataforma": [
        "Repete o mesmo segmento 300 vezes chamando de 'treinamento de reflexo'",
        "Guarda save states mas considera desonesto usá-los — e ainda assim os mantém",
        "Coleta cada item opcional mesmo sem bônus algum, porque 'o mapa fica limpo'",
        "A porcentagem de conclusão do jogo tem valor emocional superior a qualquer conquista real",
        "Já dedicou mais tempo a uma plataforma opcional do que dormiu em uma semana",
        "O conceito de 'speedrun' surgiu como curiosidade inocente e virou obsessão em 48h",
        "Qualquer jogo sem 100% de completude é classificado como 'inacabado' no catálogo mental",
    ],
    "mmo": [
        "O servidor é a família real — os outros são apenas conhecidos circunstanciais",
        "Já faltou a compromissos reais por causa de raid agendado com desconhecidos online",
        "O personagem virtual tem mais horas investidas do que qualquer relacionamento real",
        "Considera 'endgame' o único conteúdo que justifica as 2.000h iniciais de investimento",
        "Já calculou o custo-benefício da assinatura mensal com rigor de analista financeiro",
        "Guild drama gera mais angústia emocional do que qualquer problema concreto da vida real",
        "O patch de equilíbrio tem mais impacto no humor semanal do que qualquer notícia",
    ],
}

SPECIAL_SYMPTOMS = {
    "mono_library": "Pagou por uma biblioteca de {total} jogos mas só sabe o nome de um — e provavelmente nem terminou 🎮",
    "backlog_cemetery": "Possui {total} jogos na biblioteca mas {played} deles têm mais de 30min — curador dedicado do maior cemitério digital da região",
    "high_hours": "Acumulou {hours}h em {game} — isso dá {days} dias seguidos sem dormir, sem comer, sem sair de casa. Completamente normal.",
    "low_hours": "Comprou {game} e jogou exatamente {hours}h antes de abandonar para nunca mais abrir — o jogo não merecia nem o espaço no HD",
    "diverse_library": "Gosto tão eclético que o próprio Steam não sabe em qual algoritmo encaixar esse perfil",
}


# Merge new generated content
from ._new_content import NEW_SYMPTOMS as _NEW_SYM
for _cat, _syms in _NEW_SYM.items():
    SYMPTOMS.setdefault(_cat, []).extend(_syms)
