name: Deploy Backend (Render)

on:
  workflow_dispatch: # apenas manual, não dispara no push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
